### PR TITLE
fix: update STYLE peer dependency too

### PR DESCRIPTION
**Pull request by ChasNelson1990**
## Description

Turns out we updated the devDep but not the peerDep for the STYLE 9->13 upgrade this morning. This fixes that and runs `npm update`.

### CODE REVIEW

**Comment by ChasNelson1990** [comment]
Er, @cooper667, is this BrowserStack failure the one you and @philipjackson were discussing this morning?

**Comment by cooper667** [comment]
> Er, @cooper667, is this BrowserStack failure the one you and @philipjackson were discussing this morning?

no, that's a jest one in dominate. no idea what BS issue is (there's a few)

**Comment by ChasNelson1990** [comment]
> no, that's a jest one in dominate. no idea what BS issue is (there's a few)

Will rerun then!

**Comment by ChasNelson1990** [comment]
> no, that's a jest one in dominate. no idea what BS issue is (there's a few)

To be fair, this is actually a jest problem not a BS problem?

**Comment by ChasNelson1990** [comment]
Something to do with node modules not being transformed?

**Review by philipjackson — APPROVED** [review]

**Pull request merged**
