### PR TITLE
feat: View and edit users assigned to a project

### PR DESCRIPTION
**Pull request by SilviaZeta**
## Description
replaces `InviteDialog` with `EditProjectDialog`, which displays the users added to a project (both current users, in black, and users with a pending invitation, in grey) and allows to edit the user assignment, adding or removing users.

addresses #170 

## Checklist:

Put an `x` in the boxes that apply to this pull request (you can also fill these out after opening the pull request). If you're unsure about any of these, don't hesitate to leave a comment on this pull request!

- [ ] I have read the gliff.ai Contribution Guide.
- [ ] I have requested to **pull a branch** and not from main.
- [ ] I have checked all commit message styles match the requested structure.
- [ ] My code follows the style guidelines of this project.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have performed a self-review of my own code.
- [ ] I have assigned **3 or less** reviewers.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] My changes generate no new warnings.
- [ ] I have made corresponding changes to the documentation.
- [ ] New database changes have been committed.
- [ ] If appropriate, I have bumped any version numbers.

### CODE REVIEW

**Review by ChrisBaidoo — DISMISSED** [review]

**Comment by joshuajames-smith** [comment]
### 🚧 To Be Continued 🚧

This PR is ideally wanting to be closed and merged. It works as it currently stands, but the following are elements me and @SilviaZeta chatted about which will be picked up in another issue/PR to polish this off.

_Original design:_ #170 

Screenshot 2022-01-19 at 10 01 06
Screenshot 2022-01-19 at 10 54 45

_Current design:_

Screenshot 2022-01-19 at 14 47 46
Screenshot 2022-01-19 at 10 55 04

- [ ] The dialogue could be wider to support long names and email addresses better?
- [ ] The design has a another `text field` above the `user assign` to edit the project name separated by a grey line (edge-to-edge). Is this for another PR altogether?

- [ ] `User Emails` should be replaced with `User First and Last Names` for a better visual and UX – the dropdown menu will contain both for clarity.
- [ ] The dropdown menu containing `List of Users` stays highlighted as grey when selected – the UX pattern across other UI work uses the grey bar as the `hover` state for the mouse and doesn't stay active.
- [ ] The `User Input (text field)` should act as a search box with the ability for users to type in, with the drop menu only offering a list of users which met the input, i.e. input: `jos` dropdownmenu: `Josh Smith`.
- [ ] Look into how to speed up or avoid needing to fetch data to update users. If a team owner clicks to add a user to the project, their name should ideally appear instantly in the black boxes. This could be superficial while the platform has a slower backend to make the assignment happen? 
- [ ] [depends on ^] The 'update' button would then need to be moved to bottom-right and renamed 'confirm' (grey when no changes made, grey when changes made to prompt user to confirm changes)

- [ ] The `MANAGE: Projects` board view has a top row with describes the column contents. Could this have some more padding above and below the text?

**Review by joshuajames-smith — DISMISSED** [review]

**Comment by SilviaZeta** [comment]
thanks @joshuajames-smith! I've addressed the second comment and referenced your feedback in a new issue (#247).

**Review by joshuajames-smith — CHANGES_REQUESTED** [review]
Thanks for adding the `Project Name` UI element! It is currently a `downdrop list` but just needs to be a `[text field](https://mui.com/components/text-fields/#basic-textfield)` – last change for this PR before picking it back up in the next one?

**Comment by SilviaZeta** [comment]
> Thanks for adding the `Project Name` UI element! It is currently a `downdrop list` but just needs to be a `[text field](https://mui.com/components/text-fields/#basic-textfield)` – last change for this PR before picking it back up in the next one?

I've used an autocomplete with dropdown list, so the user can either type the project name or use the dropdown, which I think is helpful if one doesn't remember the exact name? Also, the dropdown list updates based on the input! I find the basic texfield less suited to this case, given that only a fixed set of options can be passed as input.

**Comment by joshuajames-smith** [comment]
> > Thanks for adding the `Project Name` UI element! It is currently a `downdrop list` but just needs to be a `[text field](https://mui.com/components/text-fields/#basic-textfield)` – last change for this PR before picking it back up in the next one?
> 
> I've used an autocomplete with dropdown list, so the user can either type the project name or use the dropdown, which I think is helpful if one doesn't remember the exact name? Also, the dropdown list updates based on the input! I find the basic texfield less suited to this case, given that only a fixed set of options can be passed as input.

The original intention and UX was that the `project name [text field]` enabled users to change the name of this specific project, i.e. a typo during the project creation or requiring better organisation upon having several projects open. Each `Edit Project` dialogue is pretty much independent of each other, so editing **Project 1** allows a user to edit name and assigned users but to access **Project 2** would use that corresponding `Edit Project [icon]`. If that makes sense @SilviaZeta ?

**Review by philipjackson — APPROVED** [review]

**Comment by SilviaZeta** [comment]
> > > Thanks for adding the `Project Name` UI element! It is currently a `downdrop list` but just needs to be a `[text field](https://mui.com/components/text-fields/#basic-textfield)` – last change for this PR before picking it back up in the next one?
> > 
> > 
> > I've used an autocomplete with dropdown list, so the user can either type the project name or use the dropdown, which I think is helpful if one doesn't remember the exact name? Also, the dropdown list updates based on the input! I find the basic texfield less suited to this case, given that only a fixed set of options can be passed as input.
> 
> The original intention and UX was that the `Project Name [text field]` enabled users to change the name of this specific project, i.e. a typo during the project creation or requiring better organisation upon having several projects open. Each `Edit Project` dialogue is pretty much independent of each other, so editing **Project 1** allows a user to edit name and assigned users but to access **Project 2** would use that corresponding `Edit Project [icon]`. If that makes sense @SilviaZeta ?

Ah! Ok, my misunderstanding. I thought the field was for selecting a different project, not for renaming. I'll change it.

**Review by ChrisBaidoo — APPROVED** [review]

**Review by joshuajames-smith — APPROVED** [review]

**Review by ChrisBaidoo — DISMISSED** [review]

**Review by ChasNelson1990 — CHANGES_REQUESTED** [review]
Should there be some Percy snapshots added for the new dialog?

**Comment by SilviaZeta** [comment]
> Should there be some Percy snapshots added for the new dialog?

Yes! Can we keep snapshots for another PR? I want to merge this one in ASAP as it is becoming ancient and is putting other PRs on hold, plus the visual still needs polishing..

**Comment by ChasNelson1990** [comment]
> Yes! Can we keep snapshots for another PR? I want to merge this one in ASAP as it is becoming ancient and is putting other PRs on hold, plus the visual still needs polishing..

Yep, can you create a test request for it please?

**Review by ChasNelson1990 — APPROVED** [review]

**Review by ChrisBaidoo — APPROVED** [review]

**Pull request merged**
